- name: Log in dockerhub
  docker_login:
    username: "{{ username }}"
    password: "{{ password }}"

- name: Pull jenkins image
  docker_image:
    name: "{{ container_image }}"
    source: pull
  register: result

- name: Create volumes
  docker_container:
    image: "{{ container_image }}"
    name: jenkins-data

- name: Create container
  docker_container:
    image: "{{ container_image }}"
    name: jenkins
    volumes_from: jenkins-data
    state: started
    restart: yes
    ports:
      - "8080:8080"

- name: Save token to variable
  shell: docker exec -it jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: result

- name: Get token
  debug:
    var: result.stdout


