---
- hosts: webservers
  become: true

  tasks:
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Update packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce

    - name: Copy config.json
      copy:
        src: ../files/config.json
        dest: /root/.docker/config.json
        owner: root
        mode: 0600

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: nexus.mm.moneyman.ru
        username: mm.dev
        password: "{{ lookup('file', '../files/config.json')}}"